openapi: 3.0.0
info:
  title: Launchpad API
  description: API for managing space launchpads
  version: 1.0.0

servers:
  - url: "http://localhost:3000"
    description: "Development server"

paths:
  /launchpads:
    get:
      summary: Get all launchpads
      operationId: getAllLaunchpads
      description: Retrieve a list of launchpads, optionally filtered by status.
      parameters:
        - name: status
          in: query
          description: The status of the launchpad (e.g., 'active', 'inactive').
          required: false
          schema:
            type: string
            enum:
              - active
              - retired
              - under-construction
            default: active
      tags:
        - Launchpads
      responses:
        "200":
          description: A list of launchpads
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Launchpad"
        "400":
          description: Bad request if invalid status is passed.
  /closest:
    get:
      summary: Get the closest launchpad
      description: Returns the closest launchpad based on user latitude and longitude.
      parameters:
        - name: latitude
          in: query
          required: true
          schema:
            type: number
            format: float
            minimum: -90
            maximum: 90
          description: Latitude of the location (between -90 and 90).
        - name: longitude
          in: query
          required: true
          schema:
            type: number
            format: float
            minimum: -180
            maximum: 180
          description: Longitude of the location (between -180 and 180).
      responses:
        "200":
          description: Successfully retrieved the closest launchpad.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Launchpad"
        "400":
          description: Invalid coordinates.
        "500":
          description: Server error.
    post:
      summary: Create a new launchpad
      operationId: createLaunchpad
      tags:
        - Launchpads
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Launchpad"
      responses:
        "201":
          description: Launchpad created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Launchpad"
        "400":
          description: Invalid request payload

  /launchpads/{id}:
    get:
      summary: Get a specific launchpad by ID
      operationId: getLaunchpadById
      tags:
        - Launchpads
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "5e9e4501f5090910d4566f83"
          description: The ID of the launchpad to retrieve
      responses:
        "200":
          description: Launchpad details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Launchpad"
        "404":
          description: Launchpad not found

    put:
      summary: Update a launchpad by ID
      operationId: updateLaunchpad
      tags:
        - Launchpads
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "5e9e4501f5090910d4566f83"
          description: The ID of the launchpad to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Launchpad"
      responses:
        "200":
          description: Launchpad updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Launchpad"
        "400":
          description: Invalid request payload
        "404":
          description: Launchpad not found

    delete:
      summary: Delete a launchpad by ID
      operationId: deleteLaunchpad
      tags:
        - Launchpads
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "5e9e4501f5090910d4566f83"
          description: The ID of the launchpad to delete
      responses:
        "204":
          description: Launchpad deleted successfully
        "404":
          description: Launchpad not found

components:
  schemas:
    Launchpad:
      type: object
      properties:
        id:
          type: string
          description: "Unique identifier for the launchpad"
        name:
          type: string
          description: "Short name of the launchpad"
        full_name:
          type: string
          description: "Full official name of the launchpad"
        locality:
          type: string
          nullable: true
          description: "Locality of the launchpad"
        region:
          type: array
          items:
            type: string
          description: "Region(s) where the launchpad is located"
        latitude:
          type: number
          format: double
          nullable: true
          description: "Latitude coordinate"
        longitude:
          type: number
          format: double
          nullable: true
          description: "Longitude coordinate"
        launch_attempts:
          type: integer
          nullable: true
          description: "Total number of launch attempts from this launchpad"
        launch_successes:
          type: integer
          nullable: true
          description: "Total number of successful launches"
        rockets:
          type: array
          items:
            type: string
          description: "List of rocket IDs associated with the launchpad"
        timezone:
          type: string
          nullable: true
          description: "Timezone of the launchpad"
        status:
          type: string
          nullable: true
          description: "Current status of the launchpad (e.g., active, retired)"
        details:
          type: string
          nullable: true
          description: "Additional details about the launchpad"
        images:
          type: object
          additionalProperties: true
          nullable: true
          description: "JSON object containing images related to the launchpad"
        launches:
          type: array
          items:
            type: string
          description: "List of launch IDs from this launchpad"
      required:
        - id
        - name
        - full_name
